from typing import Protocol


class StorageBackend(Protocol):
    """Sync storage interface — safe for Celery workers."""

    def upload(self, key: str, data: bytes) -> None: ...
    def download(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...


class AsyncStorageBackend(Protocol):
    """Async storage interface — use in FastAPI route handlers."""

    async def async_upload(self, key: str, data: bytes) -> None: ...
    async def async_download(self, key: str) -> bytes: ...
    async def async_exists(self, key: str) -> bool: ...
    async def async_delete(self, key: str) -> None: ...
