"""reconcile model schema drift phase 2

Revision ID: 3544918ecc01
Revises: 0030_datasource_actor_user
Create Date: 2026-05-23 09:29:04.601698

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3544918ecc01'
down_revision: str | None = '0030_datasource_actor_user'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_definitions', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('agent_definitions', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'disabled', name='agent_status'),
               nullable=False,
               existing_server_default=sa.text("'draft'::agent_status"))
    op.alter_column('agent_definitions', 'system_prompt',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('agent_definitions', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'gpt-4o'::character varying"))
    op.alter_column('agent_definitions', 'allowed_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_definitions', 'max_steps_per_run',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('agent_definitions', 'max_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('300'))
    op.alter_column('agent_definitions', 'max_tokens_per_run',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100000'))
    op.alter_column('agent_definitions', 'sandbox_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agent_definitions', 'memory_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_definitions', 'governance_policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_definitions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_definitions', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_agent_definitions_deleted_at'), table_name='agent_definitions')
    op.alter_column('agent_instances', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'paused', 'completed', 'failed', 'cancelled', name='instance_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::instance_status"))
    op.alter_column('agent_instances', 'steps_executed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_instances', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_instances', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('agent_instances', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_instances', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_memory_entries', 'namespace',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('agent_memory_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_memory_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_policies', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('agent_policies', 'allowed_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_policies', 'denied_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_policies', 'require_approval_for',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_policies', 'approval_timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('300'))
    op.alter_column('agent_policies', 'approval_default_action',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'deny'::character varying"))
    op.alter_column('agent_policies', 'rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_policies', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_sessions', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'expired', name='session_status'),
               nullable=False,
               existing_server_default=sa.text("'active'::session_status"))
    op.alter_column('agent_sessions', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_sessions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('connector_definitions', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('connector_definitions', 'icon',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Plug'::character varying"))
    op.alter_column('connector_definitions', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'custom'::character varying"))
    op.alter_column('connector_definitions', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('connector_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('connector_definitions', 'version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.drop_index(op.f('ix_jobs_deleted_at'), table_name='jobs')
    op.drop_index(op.f('ix_prompt_templates_deleted_at'), table_name='prompt_templates')
    op.alter_column('tenant_connections', 'status',
               existing_type=postgresql.ENUM('active', 'degraded', 'expired', 'disconnected', 'error', name='connectionstatus'),
               nullable=False,
               existing_server_default=sa.text("'active'::connectionstatus"))
    op.drop_index(op.f('ix_tenant_connections_deleted_at'), table_name='tenant_connections')
    op.alter_column('tenant_credentials', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant_tools', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tenant_tools', 'source',
               existing_type=postgresql.ENUM('builtin', 'tenant', 'marketplace', name='tool_source'),
               nullable=False,
               existing_server_default=sa.text("'tenant'::tool_source"))
    op.alter_column('tenant_tools', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'auth_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant_tools', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tenant_tools_deleted_at'), table_name='tenant_tools')
    op.drop_index(op.f('ix_tenants_deleted_at'), table_name='tenants')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_wallet_transactions_tenant_id'), table_name='wallet_transactions')
    op.alter_column('workflow_definitions', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('workflow_definitions', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'disabled', name='workflow_status'),
               nullable=False,
               existing_server_default=sa.text("'draft'::workflow_status"))
    op.alter_column('workflow_definitions', 'governance',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_definitions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_definitions', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_workflow_definitions_deleted_at'), table_name='workflow_definitions')
    op.alter_column('workflow_runs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'waiting_approval', 'completed', 'failed', 'cancelled', name='workflow_run_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::workflow_run_status"))
    op.alter_column('workflow_runs', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_runs', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_runs', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_runs', 'total_steps',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_runs', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_runs', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_runs', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('workflow_runs', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_runs', 'total_steps',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_runs', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_runs', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_runs', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_runs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'waiting_approval', 'completed', 'failed', 'cancelled', name='workflow_run_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::workflow_run_status"))
    op.create_index(op.f('ix_workflow_definitions_deleted_at'), 'workflow_definitions', ['deleted_at'], unique=False)
    op.alter_column('workflow_definitions', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('workflow_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_definitions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_definitions', 'governance',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflow_definitions', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'disabled', name='workflow_status'),
               nullable=True,
               existing_server_default=sa.text("'draft'::workflow_status"))
    op.alter_column('workflow_definitions', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.create_index(op.f('ix_wallet_transactions_tenant_id'), 'wallet_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tenant_tools_deleted_at'), 'tenant_tools', ['deleted_at'], unique=False)
    op.alter_column('tenant_tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_tools', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant_tools', 'auth_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenant_tools', 'source',
               existing_type=postgresql.ENUM('builtin', 'tenant', 'marketplace', name='tool_source'),
               nullable=True,
               existing_server_default=sa.text("'tenant'::tool_source"))
    op.alter_column('tenant_tools', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tenant_credentials', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_tenant_connections_deleted_at'), 'tenant_connections', ['deleted_at'], unique=False)
    op.alter_column('tenant_connections', 'status',
               existing_type=postgresql.ENUM('active', 'degraded', 'expired', 'disconnected', 'error', name='connectionstatus'),
               nullable=True,
               existing_server_default=sa.text("'active'::connectionstatus"))
    op.create_index(op.f('ix_prompt_templates_deleted_at'), 'prompt_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_jobs_deleted_at'), 'jobs', ['deleted_at'], unique=False)
    op.alter_column('connector_definitions', 'version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('connector_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('connector_definitions', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('connector_definitions', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'custom'::character varying"))
    op.alter_column('connector_definitions', 'icon',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Plug'::character varying"))
    op.alter_column('connector_definitions', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('agent_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_sessions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_sessions', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_sessions', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'expired', name='session_status'),
               nullable=True,
               existing_server_default=sa.text("'active'::session_status"))
    op.alter_column('agent_policies', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_policies', 'rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_policies', 'approval_default_action',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'deny'::character varying"))
    op.alter_column('agent_policies', 'approval_timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('300'))
    op.alter_column('agent_policies', 'require_approval_for',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_policies', 'denied_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_policies', 'allowed_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_policies', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('agent_memory_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_memory_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_memory_entries', 'namespace',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('agent_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_instances', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_instances', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_instances', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('agent_instances', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_instances', 'steps_executed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_instances', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'paused', 'completed', 'failed', 'cancelled', name='instance_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::instance_status"))
    op.create_index(op.f('ix_agent_definitions_deleted_at'), 'agent_definitions', ['deleted_at'], unique=False)
    op.alter_column('agent_definitions', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_definitions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_definitions', 'governance_policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_definitions', 'memory_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_definitions', 'sandbox_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('agent_definitions', 'max_tokens_per_run',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100000'))
    op.alter_column('agent_definitions', 'max_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('300'))
    op.alter_column('agent_definitions', 'max_steps_per_run',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('agent_definitions', 'allowed_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agent_definitions', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'gpt-4o'::character varying"))
    op.alter_column('agent_definitions', 'system_prompt',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('agent_definitions', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'disabled', name='agent_status'),
               nullable=True,
               existing_server_default=sa.text("'draft'::agent_status"))
    op.alter_column('agent_definitions', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
