from typing import Protocol


class StorageBackend(Protocol):
    def upload(self, key: str, data: bytes) -> None: ...
    def download(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
