apiVersion: v1
kind: Service
metadata:
  name: nxs-api
  namespace: nxs
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: nxs
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: nxs
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
