/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProviderKeysRouteImport } from './routes/provider-keys'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth/callback/$provider'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/webhooks.lazy').then((d) => d.Route))
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/verify-email.lazy').then((d) => d.Route))
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/team.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const ProviderKeysRoute = ProviderKeysRouteImport.update({
  id: '/provider-keys',
  path: '/provider-keys',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/provider-keys.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/jobs.lazy').then((d) => d.Route))
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/files.lazy').then((d) => d.Route))
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/developers.lazy').then((d) => d.Route))
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/billing.lazy').then((d) => d.Route))
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/audit-log.lazy').then((d) => d.Route))
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/api-keys.lazy').then((d) => d.Route))
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agents.lazy').then((d) => d.Route))
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/accept-invitation.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/callback/$provider.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/developers': typeof DevelopersRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/provider-keys': typeof ProviderKeysRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webhooks': typeof WebhooksRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/developers': typeof DevelopersRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/provider-keys': typeof ProviderKeysRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webhooks': typeof WebhooksRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/developers': typeof DevelopersRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/provider-keys': typeof ProviderKeysRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webhooks': typeof WebhooksRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/billing'
    | '/chat'
    | '/developers'
    | '/files'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/provider-keys'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/team'
    | '/verify-email'
    | '/webhooks'
    | '/auth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/billing'
    | '/chat'
    | '/developers'
    | '/files'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/provider-keys'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/team'
    | '/verify-email'
    | '/webhooks'
    | '/auth/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/billing'
    | '/chat'
    | '/developers'
    | '/files'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/provider-keys'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/team'
    | '/verify-email'
    | '/webhooks'
    | '/auth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AgentsRoute: typeof AgentsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AuditLogRoute: typeof AuditLogRoute
  BillingRoute: typeof BillingRoute
  ChatRoute: typeof ChatRoute
  DevelopersRoute: typeof DevelopersRoute
  FilesRoute: typeof FilesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  ProviderKeysRoute: typeof ProviderKeysRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WebhooksRoute: typeof WebhooksRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-keys': {
      id: '/provider-keys'
      path: '/provider-keys'
      fullPath: '/provider-keys'
      preLoaderRoute: typeof ProviderKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AgentsRoute: AgentsRoute,
  ApiKeysRoute: ApiKeysRoute,
  AuditLogRoute: AuditLogRoute,
  BillingRoute: BillingRoute,
  ChatRoute: ChatRoute,
  DevelopersRoute: DevelopersRoute,
  FilesRoute: FilesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  ProviderKeysRoute: ProviderKeysRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WebhooksRoute: WebhooksRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
