/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProviderKeysRouteImport } from './routes/provider-keys'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as SettingsWebhooksRouteImport } from './routes/settings.webhooks'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as SettingsDangerRouteImport } from './routes/settings.danger'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsAuditLogRouteImport } from './routes/settings.audit-log'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'
import { Route as AgentsWorkspaceRouteImport } from './routes/agents.workspace'
import { Route as AgentsSessionsRouteImport } from './routes/agents.sessions'
import { Route as AgentsChatRouteImport } from './routes/agents.chat'
import { Route as AgentsInstanceIdRouteImport } from './routes/agents.$instanceId'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth/callback/$provider'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/webhooks.lazy').then((d) => d.Route))
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/verify-email.lazy').then((d) => d.Route))
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/team.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const ProviderKeysRoute = ProviderKeysRouteImport.update({
  id: '/provider-keys',
  path: '/provider-keys',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/provider-keys.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/jobs.lazy').then((d) => d.Route))
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/files.lazy').then((d) => d.Route))
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/developers.lazy').then((d) => d.Route))
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/billing.lazy').then((d) => d.Route))
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/audit-log.lazy').then((d) => d.Route))
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/api-keys.lazy').then((d) => d.Route))
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agents.lazy').then((d) => d.Route))
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/accept-invitation.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any).lazy(() => import('./routes/agents.index.lazy').then((d) => d.Route))
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.webhooks.lazy').then((d) => d.Route),
)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() => import('./routes/settings.team.lazy').then((d) => d.Route))
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.security.lazy').then((d) => d.Route),
)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.providers.lazy').then((d) => d.Route),
)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.general.lazy').then((d) => d.Route),
)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() => import('./routes/settings.data.lazy').then((d) => d.Route))
const SettingsDangerRoute = SettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.danger.lazy').then((d) => d.Route),
)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.billing.lazy').then((d) => d.Route),
)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.audit-log.lazy').then((d) => d.Route),
)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.api-keys.lazy').then((d) => d.Route),
)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.agents.lazy').then((d) => d.Route),
)
const AgentsWorkspaceRoute = AgentsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AgentsRoute,
} as any).lazy(() =>
  import('./routes/agents.workspace.lazy').then((d) => d.Route),
)
const AgentsSessionsRoute = AgentsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AgentsRoute,
} as any).lazy(() =>
  import('./routes/agents.sessions.lazy').then((d) => d.Route),
)
const AgentsChatRoute = AgentsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentsRoute,
} as any).lazy(() => import('./routes/agents.chat.lazy').then((d) => d.Route))
const AgentsInstanceIdRoute = AgentsInstanceIdRouteImport.update({
  id: '/$instanceId',
  path: '/$instanceId',
  getParentRoute: () => AgentsRoute,
} as any).lazy(() =>
  import('./routes/agents.$instanceId.lazy').then((d) => d.Route),
)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/callback/$provider.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/agents': typeof AgentsRouteWithChildren
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/developers': typeof DevelopersRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/provider-keys': typeof ProviderKeysRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webhooks': typeof WebhooksRoute
  '/agents/$instanceId': typeof AgentsInstanceIdRoute
  '/agents/chat': typeof AgentsChatRoute
  '/agents/sessions': typeof AgentsSessionsRoute
  '/agents/workspace': typeof AgentsWorkspaceRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/agents/': typeof AgentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/developers': typeof DevelopersRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/provider-keys': typeof ProviderKeysRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webhooks': typeof WebhooksRoute
  '/agents/$instanceId': typeof AgentsInstanceIdRoute
  '/agents/chat': typeof AgentsChatRoute
  '/agents/sessions': typeof AgentsSessionsRoute
  '/agents/workspace': typeof AgentsWorkspaceRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/agents': typeof AgentsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/agents': typeof AgentsRouteWithChildren
  '/api-keys': typeof ApiKeysRoute
  '/audit-log': typeof AuditLogRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/developers': typeof DevelopersRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/provider-keys': typeof ProviderKeysRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webhooks': typeof WebhooksRoute
  '/agents/$instanceId': typeof AgentsInstanceIdRoute
  '/agents/chat': typeof AgentsChatRoute
  '/agents/sessions': typeof AgentsSessionsRoute
  '/agents/workspace': typeof AgentsWorkspaceRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/agents/': typeof AgentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/billing'
    | '/chat'
    | '/developers'
    | '/files'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/provider-keys'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/team'
    | '/verify-email'
    | '/webhooks'
    | '/agents/$instanceId'
    | '/agents/chat'
    | '/agents/sessions'
    | '/agents/workspace'
    | '/settings/agents'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/general'
    | '/settings/providers'
    | '/settings/security'
    | '/settings/team'
    | '/settings/webhooks'
    | '/agents/'
    | '/settings/'
    | '/auth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/api-keys'
    | '/audit-log'
    | '/billing'
    | '/chat'
    | '/developers'
    | '/files'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/provider-keys'
    | '/register'
    | '/reset-password'
    | '/team'
    | '/verify-email'
    | '/webhooks'
    | '/agents/$instanceId'
    | '/agents/chat'
    | '/agents/sessions'
    | '/agents/workspace'
    | '/settings/agents'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/general'
    | '/settings/providers'
    | '/settings/security'
    | '/settings/team'
    | '/settings/webhooks'
    | '/agents'
    | '/settings'
    | '/auth/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/agents'
    | '/api-keys'
    | '/audit-log'
    | '/billing'
    | '/chat'
    | '/developers'
    | '/files'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/provider-keys'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/team'
    | '/verify-email'
    | '/webhooks'
    | '/agents/$instanceId'
    | '/agents/chat'
    | '/agents/sessions'
    | '/agents/workspace'
    | '/settings/agents'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/general'
    | '/settings/providers'
    | '/settings/security'
    | '/settings/team'
    | '/settings/webhooks'
    | '/agents/'
    | '/settings/'
    | '/auth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApiKeysRoute: typeof ApiKeysRoute
  AuditLogRoute: typeof AuditLogRoute
  BillingRoute: typeof BillingRoute
  ChatRoute: typeof ChatRoute
  DevelopersRoute: typeof DevelopersRoute
  FilesRoute: typeof FilesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  ProviderKeysRoute: typeof ProviderKeysRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TeamRoute: typeof TeamRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WebhooksRoute: typeof WebhooksRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-keys': {
      id: '/provider-keys'
      path: '/provider-keys'
      fullPath: '/provider-keys'
      preLoaderRoute: typeof ProviderKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/settings/webhooks': {
      id: '/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/danger': {
      id: '/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof SettingsDangerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audit-log': {
      id: '/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/agents/workspace': {
      id: '/agents/workspace'
      path: '/workspace'
      fullPath: '/agents/workspace'
      preLoaderRoute: typeof AgentsWorkspaceRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/sessions': {
      id: '/agents/sessions'
      path: '/sessions'
      fullPath: '/agents/sessions'
      preLoaderRoute: typeof AgentsSessionsRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/chat': {
      id: '/agents/chat'
      path: '/chat'
      fullPath: '/agents/chat'
      preLoaderRoute: typeof AgentsChatRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$instanceId': {
      id: '/agents/$instanceId'
      path: '/$instanceId'
      fullPath: '/agents/$instanceId'
      preLoaderRoute: typeof AgentsInstanceIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsInstanceIdRoute: typeof AgentsInstanceIdRoute
  AgentsChatRoute: typeof AgentsChatRoute
  AgentsSessionsRoute: typeof AgentsSessionsRoute
  AgentsWorkspaceRoute: typeof AgentsWorkspaceRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsInstanceIdRoute: AgentsInstanceIdRoute,
  AgentsChatRoute: AgentsChatRoute,
  AgentsSessionsRoute: AgentsSessionsRoute,
  AgentsWorkspaceRoute: AgentsWorkspaceRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface SettingsRouteChildren {
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsDangerRoute: typeof SettingsDangerRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsDangerRoute: SettingsDangerRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApiKeysRoute: ApiKeysRoute,
  AuditLogRoute: AuditLogRoute,
  BillingRoute: BillingRoute,
  ChatRoute: ChatRoute,
  DevelopersRoute: DevelopersRoute,
  FilesRoute: FilesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  ProviderKeysRoute: ProviderKeysRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TeamRoute: TeamRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WebhooksRoute: WebhooksRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
